### ISSUE TITLE
Main Page icon fixes 

### ISSUE THREAD

**Issue by haksuman** [SDG-AI-Lab/Digital_Technologies_Radar#172]
- [x] - The UNDP icon which is in upper left should be direct link to UNDP website (https://www.undp.org/)

- [x] - The route buttons could have the same blue color as UNDP’s one. 

- [x] - Below icons for “Connecting Business Initiative, UNDP, SDG AI LAB” should also be clickable.

**Comment by OzgeOzkaya** [comment]
Dear Hakan, seems like we will recruit a graphic designer online volunteer for this page. The logos are a bit hard to fit in to the page in a good way. Help of a graphic designer would be really good for this task. You may drop this one for now. Thank you!

**Comment by haksuman** [comment]
The Issue with UNDP & SDG-AI icons occurs due to different icon components in mobile app view. This issue has been fixed with necessary corrections in mobile app view. About fitting icons in a responsive design, we may create another issue
