### ISSUE TITLE
Fix home page bacground with the new background images and put launch radar button

### ISSUE THREAD

**Issue by OzgeOzkaya** [SDG-AI-Lab/Digital_Technologies_Radar#197]
Please use this image in the desktop view and add one 'launch radar' button between the text and the titles:

![bg5](https://user-images.githubusercontent.com/28465079/192218691-1d36b53c-ed53-425c-adb5-7dd2cfb4eea2.jpg)

Use this image in the mobile view and add launh radar button to the center of the mobile screens
![radarmobile](https://user-images.githubusercontent.com/28465079/192218731-bfa9ea51-8e1d-4f1f-8b06-5bb0b97d14b9.jpg)

**Comment by jacksono** [comment]
@OzgeOzkaya  for the desktop view we will already have the icons for the 2 organisations being shown on the side bar, will it be a duplication to show them again on the background image?

<img width="1504" alt="Screenshot 2022-10-04 at 09 23 22" src="https://user-images.githubusercontent.com/4943363/193749299-e0682c0a-5f60-468d-856c-5e5154179409.png">

**Comment by OzgeOzkaya** [comment]
Yes, please. No worries about the duplication
