### ISSUE TITLE
Stick the back button and filtering button to the top for mobile view

### ISSUE THREAD

**Issue by OzgeOzkaya** [SDG-AI-Lab/Digital_Technologies_Radar#202]
The back and filtering buttons are scrolling with the page and it causes overlapping:

<img width="234" alt="Screenshot_151" src="https://user-images.githubusercontent.com/28465079/192479596-3354189d-eed2-4114-a45a-50067d15d6b7.png">

Stick them to the top so they wont scroll with the scrolling action:

<img width="235" alt="Screenshot_152" src="https://user-images.githubusercontent.com/28465079/192479739-665a6d01-2a7c-4175-9b06-34c3c0f50780.png">

**Comment by jacksono** [comment]
@OzgeOzkaya Kindly check this again. I added a fix for this in my previous PR. Let me know if the behaviour is still off.

**Comment by OzgeOzkaya** [comment]
Hi @jacksono ! The back button is sticked to the top, however the filtering button still moves with the scroll

**Comment by jacksono** [comment]
Hi @OzgeOzkaya ,  thats is strange because It is working well for me, See the video below.
Try hard reloading your browser and if it still does not work for you we can have a call tomorrow morning.

https://user-images.githubusercontent.com/4943363/193619068-84d510ad-3edc-406c-8df4-20cd40b1ae97.mov
