### ISSUE TITLE
Adjust the design of hovering functionality as in the mockups.

### ISSUE THREAD

**Issue by OzgeOzkaya** [SDG-AI-Lab/Digital_Technologies_Radar#81]
Tasks: 

- [ ] Adjust the design of hovering functionality as in the mockups. 
- [x] When the user hovers the radar, and once he is hovering an item, we should display a popup as per mockups. 
- [x] For us to achieve this we will need to enhance the LIB. Once again, we need to send a component specifying how we wish to display this popup. For that we can use composition and accept child parameters such as 'item' which we can then display as we please.

**Comment by nmpribeiro** [comment]
@OzgeOzkaya , do we still need to improve hovering design? (I have to admit I downplayed the priority of design fine-tune in order to improve performance)
