### ISSUE TITLE
Propose 3 different themes

### ISSUE THREAD

**Issue by OzgeOzkaya** [SDG-AI-Lab/Digital_Technologies_Radar#83]
Tasks: 

- [ ] Propose 3 different themes by changing the colors

**Comment by fluffybird2323** [comment]
Theme 1
![image](https://user-images.githubusercontent.com/43714110/160144217-8585f12f-7e2e-4060-ac53-d748be617f75.png)

Theme 2
![image](https://user-images.githubusercontent.com/43714110/160144262-9546e5dc-c300-46e6-9216-dc69ea1f1bd0.png)

Theme 3
![image](https://user-images.githubusercontent.com/43714110/160144293-571ea943-b7dc-4b9c-be52-0289bef457cf.png)

**Comment by OzgeOzkaya** [comment]
Hi @fluffybird2323! Thanks for the themes. You don't have to any task before the real recruitment. It is fine it you just mail us that you are comfortable :) 

But for avoiding future misunderstanding, "theme" includes all of the screen like all of the components on the page. So we need to propose different colored themes that covers all of the page(both main radar page and quadrant pages). However, thank you for taking action at very early stage :)
